[2020-12-21T22:12:27.755Z] ERROR something went wrong: TokenExpiredError: jwt expired (host=nox-desktop, name=network_logger, pid=2296)
[2020-12-21T22:12:42.179Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=6936)
[2020-12-21T22:14:38.787Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:14:43.805Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:14:48.818Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:14:59.918Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:04.946Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:06.426Z] ERROR something went wrong: GraphQLError: Field "addComment" argument "postID" of type "String!" is required, but it was not provided.
    at Object.leave (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ProvidedRequiredArgumentsRule.js:62:33)
    at Object.leave (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:344:29)
    at Object.leave (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:390:21)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:18.026Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:29.088Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:34.114Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:19:58.695Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=4196)
[2020-12-21T22:20:16.257Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Post.user.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=4196)
[2020-12-21T22:20:53.951Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=18776)
[2020-12-21T22:47:16.705Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:17.347Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:22.366Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:23.401Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:24.430Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:25.460Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:26.495Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:28.536Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:31.558Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:36.582Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:44.622Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:57.655Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:48:18.678Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:48:52.703Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:49:48.345Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:50:24.271Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:51:15.947Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:51:21.744Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:52:45.345Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:52:50.360Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:52:51.964Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T23:16:14.860Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=21728)
[2020-12-21T23:17:48.471Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=21728)
[2020-12-21T23:18:31.419Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=15756)
[2020-12-21T23:20:43.900Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=10376)
[2020-12-21T23:21:11.772Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10376)
[2020-12-21T23:21:17.005Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:17.011Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:18.475Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:26.099Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:26.722Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:32.098Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:59.262Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=8724)
[2020-12-21T23:22:31.981Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=8724)
[2020-12-21T23:28:01.708Z] ERROR something went wrong: GraphQLError: Field "getLikeCountFromPost" of type "LikeCountResponse!" must have a selection of subfields. Did you mean "getLikeCountFromPost { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=12664)
[2020-12-21T23:29:45.881Z] ERROR something went wrong: GraphQLError: Cannot query field "totalCount" on type "LikeCountResponse". Did you mean "likeCount"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\FieldsOnCorrectTypeRule.js:46:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11892)
[2020-12-21T23:41:53.140Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:41:56.872Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:04.577Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:04.747Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:04.917Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:34.402Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:47:30.512Z] ERROR something went wrong: GraphQLError: Field "getPosts" of type "[Post!]" must have a selection of subfields. Did you mean "getPosts { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=21628)
[2020-12-21T23:53:26.779Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:53:31.922Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Comment.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:54:36.506Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:06.871Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:18.558Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Comment.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:28.146Z] ERROR something went wrong: GraphQLError: Field "text" must not have a selection since type "String!" has no subfields.
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:33:33)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:55.494Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Post.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:58:10.439Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Post.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=4700)
[2020-12-21T23:58:46.867Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=13704)
[2020-12-22T00:01:29.326Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Comment.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=6680)
[2020-12-22T00:02:59.882Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Like.user.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=17312)
[2020-12-22T00:04:24.837Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=17864)
[2020-12-22T00:04:38.117Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=17232)
[2020-12-22T00:04:39.188Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=17232)
[2020-12-22T22:14:44.746Z] ERROR something went wrong: Error: you already liked this post
    at CommentResolver.likeComment (H:\projects\network\network_backend\src\resolvers\comment.resolver.ts:63:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=29820)
[2020-12-22T22:16:33.407Z] ERROR something went wrong: GraphQLError: Field "followers" of type "[User!]!" must have a selection of subfields. Did you mean "followers { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=32392)
[2020-12-22T22:16:43.934Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32392)
[2020-12-22T22:20:52.177Z] ERROR something went wrong: Error: Relations "post.comments", "post.user", "post.likes", "post.likes.user", "post.comments.user", "post.comments.likes", "post.comments.likes.user" were not found; please check if relations are correct and they exist in your entities.
    at new FindRelationsNotFoundError (H:\projects\network\network_backend\src\error\FindRelationsNotFoundError.ts:7:9)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (H:\projects\network\network_backend\src\find-options\FindOptionsUtils.ts:147:23)
    at EntityManager.<anonymous> (H:\projects\network\network_backend\src\entity-manager\EntityManager.ts:788:26)
    at step (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
    at EntityManager.findOne (H:\projects\network\network_backend\node_modules\typeorm\entity-manager\EntityManager.js:508:24)
    at Repository.findOne (H:\projects\network\network_backend\src\repository\Repository.ts:370:29) (host=nox-desktop, name=network_logger, pid=31052)
[2020-12-22T22:21:34.564Z] ERROR something went wrong: Error: Relations "post.comments", "post.user", "post.likes", "post.likes.user", "post.comments.user", "post.comments.likes", "post.comments.likes.user" were not found; please check if relations are correct and they exist in your entities.
    at new FindRelationsNotFoundError (H:\projects\network\network_backend\src\error\FindRelationsNotFoundError.ts:7:9)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (H:\projects\network\network_backend\src\find-options\FindOptionsUtils.ts:147:23)
    at EntityManager.<anonymous> (H:\projects\network\network_backend\src\entity-manager\EntityManager.ts:788:26)
    at step (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
    at EntityManager.findOne (H:\projects\network\network_backend\node_modules\typeorm\entity-manager\EntityManager.js:508:24)
    at Repository.findOne (H:\projects\network\network_backend\src\repository\Repository.ts:370:29) (host=nox-desktop, name=network_logger, pid=31052)
[2020-12-22T22:22:30.699Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=28756)
[2020-12-22T22:22:58.127Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=5408)
[2020-12-22T22:23:10.200Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=5408)
[2020-12-22T22:23:53.551Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32712)
[2020-12-22T22:23:54.856Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32712)
[2020-12-22T22:23:59.865Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32712)
[2020-12-22T22:24:08.753Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=26612)
[2020-12-22T22:24:11.627Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=26612)
[2020-12-22T22:24:19.369Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32160)
[2020-12-22T22:24:20.233Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32160)
[2020-12-22T22:27:11.360Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=24604)
[2020-12-22T22:27:22.459Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32272)
[2020-12-22T22:27:23.840Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32272)
[2020-12-22T22:27:47.357Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32244)
[2020-12-22T22:27:48.398Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32244)
[2020-12-22T22:27:54.909Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=20120)
[2020-12-22T22:27:56.743Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=20120)
[2020-12-22T22:28:05.308Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=27352)
[2020-12-22T22:28:06.148Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=27352)
[2020-12-22T22:31:27.215Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=31440)
[2020-12-22T22:31:39.349Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=29052)
[2020-12-22T22:33:41.970Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=29768)
[2020-12-22T22:36:05.802Z] ERROR something went wrong: Error: you already liked this post
    at CommentResolver.likeComment (H:\projects\network\network_backend\src\resolvers\comment.resolver.ts:63:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=29768)
[2020-12-25T16:45:41.122Z] ERROR something went wrong: GraphQLError: Field "followers" of type "[User!]!" must have a selection of subfields. Did you mean "followers { ... }"?
    at Object.Field (/srv/backend/node_modules/graphql/validation/rules/ScalarLeafsRule.js:40:31)
    at Object.enter (/srv/backend/node_modules/graphql/language/visitor.js:323:29)
    at Object.enter (/srv/backend/node_modules/graphql/utilities/TypeInfo.js:370:25)
    at visit (/srv/backend/node_modules/graphql/language/visitor.js:243:26)
    at validate (/srv/backend/node_modules/graphql/validation/validate.js:69:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=ea7beb035c73, name=network_logger, pid=38)
[2020-12-25T16:45:57.752Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at resolveField (/srv/backend/node_modules/graphql/execution/execute.js:474:19)
    at executeFields (/srv/backend/node_modules/graphql/execution/execute.js:294:18)
    at collectAndExecuteSubfields (/srv/backend/node_modules/graphql/execution/execute.js:749:10)
    at completeObjectValue (/srv/backend/node_modules/graphql/execution/execute.js:739:10)
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:592:12)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=ea7beb035c73, name=network_logger, pid=38)
[2020-12-25T16:51:25.404Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Mutation.removeFollower.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=ea7beb035c73, name=network_logger, pid=138)
[2020-12-25T20:02:52.713Z] ERROR Error: write EPROTO 140472612833088:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) (host=cc76d8ff70ba, name=network_logger, pid=264)
[2020-12-25T20:02:52.718Z] ERROR Error: write EPROTO 140472612833088:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) (host=cc76d8ff70ba, name=network_logger, pid=264)
[2020-12-25T20:51:22.438Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (/srv/backend/src/resolvers/post.resolver.ts:96:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1041)
[2020-12-25T20:53:04.279Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.unlikePost (/srv/backend/src/resolvers/post.resolver.ts:130:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1041)
[2020-12-25T20:53:35.864Z] ERROR something went wrong: TypeError: Cannot read property 'id' of undefined
    at /srv/backend/src/resolvers/post.resolver.ts:130:33
    at Function.remove (/srv/backend/node_modules/lodash/lodash.js:7881:13)
    at PostResolver.unlikePost (/srv/backend/src/resolvers/post.resolver.ts:129:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1077)
[2020-12-25T20:55:16.365Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (/srv/backend/src/resolvers/post.resolver.ts:96:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1089)
[2020-12-25T20:55:46.748Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (/srv/backend/src/resolvers/post.resolver.ts:96:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1089)
[2020-12-25T21:00:19.363Z] ERROR something went wrong: MustBeEntityError: Cannot remove, given value must be an entity, instead "undefined" is given.
    at new MustBeEntityError (/srv/backend/src/error/MustBeEntityError.ts:8:9)
    at EntityPersistExecutor.execute (/srv/backend/src/persistence/EntityPersistExecutor.ts:45:35)
    at EntityManager.remove (/srv/backend/src/entity-manager/EntityManager.ts:362:14)
    at Repository.remove (/srv/backend/src/repository/Repository.ts:167:29)
    at PostResolver.unlikePost (/srv/backend/src/resolvers/post.resolver.ts:146:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1192)
[2020-12-25T21:05:24.264Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Mutation.likeComment.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1444)
[2020-12-25T21:05:34.294Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Mutation.likeComment.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1444)
[2020-12-25T21:06:02.629Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Mutation.likeComment.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1444)
[2020-12-25T21:06:27.545Z] ERROR something went wrong: TypeError: Cannot read property 'id' of undefined
    at /srv/backend/src/resolvers/comment.resolver.ts:94:33
    at Function.remove (/srv/backend/node_modules/lodash/lodash.js:7881:13)
    at CommentResolver.unlikeComment (/srv/backend/src/resolvers/comment.resolver.ts:93:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1444)
[2020-12-25T21:45:29.492Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Mutation.login.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T21:55:45.881Z] ERROR something went wrong: GraphQLError: Unknown operation named "Query".
    at buildExecutionContext (/srv/backend/node_modules/graphql/execution/execute.js:197:15)
    at executeImpl (/srv/backend/node_modules/graphql/execution/execute.js:103:20)
    at execute (/srv/backend/node_modules/graphql/execution/execute.js:62:35)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T21:57:06.928Z] ERROR something went wrong: Error: Access denied! You need to be authorized to perform this action!
    at /srv/backend/node_modules/type-graphql/dist/helpers/auth-middleware.js:13:44
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at async Promise.all (index 0)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T21:57:16.647Z] ERROR something went wrong: Error: Access denied! You need to be authorized to perform this action!
    at /srv/backend/node_modules/type-graphql/dist/helpers/auth-middleware.js:13:44
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at async Promise.all (index 0)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T22:06:09.523Z] ERROR something went wrong: GraphQLError: Upload literal unsupported.
    at GraphQLScalarType.parseLiteral (/srv/backend/node_modules/graphql-upload/public/GraphQLUpload.js:85:11)
    at isValidValueNode (/srv/backend/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:125:28)
    at Object.StringValue (/srv/backend/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:93:14)
    at Object.enter (/srv/backend/node_modules/graphql/language/visitor.js:323:29)
    at Object.enter (/srv/backend/node_modules/graphql/utilities/TypeInfo.js:370:25)
    at visit (/srv/backend/node_modules/graphql/language/visitor.js:243:26)
    at validate (/srv/backend/node_modules/graphql/validation/validate.js:69:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T22:06:48.850Z] ERROR something went wrong: GraphQLError: Unknown argument "image" on field "Mutation.uploadProfileImage".
    at Object.Argument (/srv/backend/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:29)
    at Object.enter (/srv/backend/node_modules/graphql/language/visitor.js:323:29)
    at Object.enter (/srv/backend/node_modules/graphql/utilities/TypeInfo.js:370:25)
    at visit (/srv/backend/node_modules/graphql/language/visitor.js:243:26)
    at validate (/srv/backend/node_modules/graphql/validation/validate.js:69:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T22:07:52.742Z] ERROR something went wrong: GraphQLError: Unknown argument "image" on field "Mutation.uploadProfileImage".
    at Object.Argument (/srv/backend/node_modules/graphql/validation/rules/KnownArgumentNamesRule.js:46:29)
    at Object.enter (/srv/backend/node_modules/graphql/language/visitor.js:323:29)
    at Object.enter (/srv/backend/node_modules/graphql/utilities/TypeInfo.js:370:25)
    at visit (/srv/backend/node_modules/graphql/language/visitor.js:243:26)
    at validate (/srv/backend/node_modules/graphql/validation/validate.js:69:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T22:16:47.535Z] ERROR something went wrong: GraphQLError: Variable "$file" of non-null type "Upload!" must not be null.
    at _loop (/srv/backend/node_modules/graphql/execution/values.js:105:15)
    at coerceVariableValues (/srv/backend/node_modules/graphql/execution/values.js:121:16)
    at getVariableValues (/srv/backend/node_modules/graphql/execution/values.js:50:19)
    at buildExecutionContext (/srv/backend/node_modules/graphql/execution/execute.js:205:61)
    at executeImpl (/srv/backend/node_modules/graphql/execution/execute.js:103:20)
    at execute (/srv/backend/node_modules/graphql/execution/execute.js:62:35)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T22:17:28.838Z] ERROR something went wrong: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ReadStream
    at WriteStream.Writable.write (internal/streams/writable.js:285:13)
    at UserResolver.uploadProfileImage (/srv/backend/src/resolvers/user.resolver.ts:114:8)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/create.js:31:98
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1456)
[2020-12-25T22:19:19.265Z] ERROR something went wrong: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ReadStream
    at WriteStream.Writable.write (internal/streams/writable.js:285:13)
    at UserResolver.uploadProfileImage (/srv/backend/src/resolvers/user.resolver.ts:113:8)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/create.js:31:98
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/srv/backend/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1468)
[2020-12-25T22:33:02.439Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Mutation.uploadProfileImage.
    at completeValue (/srv/backend/node_modules/graphql/execution/execute.js:561:13)
    at /srv/backend/node_modules/graphql/execution/execute.js:471:16
    at graphqlMiddleware (/srv/backend/node_modules/express-graphql/index.js:125:26) (host=cc76d8ff70ba, name=network_logger, pid=1614)
[2020-12-25T22:48:20.344Z] ERROR Error: ENOENT: no such file or directory, open '/tmp/26b73c24-213a-40da-a024-3d20fa8bb37f' (host=cc76d8ff70ba, name=network_logger, pid=79)
[2020-12-25T22:48:59.375Z] ERROR Error: ENOENT: no such file or directory, open '/tmp/ada424cd38781f34d172daccd0be80c5.jpg' (host=cc76d8ff70ba, name=network_logger, pid=103)
[2020-12-25T22:49:45.031Z] ERROR Error: ENOENT: no such file or directory, open '/tmp/ada424cd38781f34d172daccd0be80c5.jpg' (host=cc76d8ff70ba, name=network_logger, pid=115)
[2020-12-25T22:52:45.144Z] ERROR Error: ENOENT: no such file or directory, open '/tmp/concept idea.png' (host=cc76d8ff70ba, name=network_logger, pid=163)
[2020-12-25T22:57:20.444Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/concept idea.png' (host=cc76d8ff70ba, name=network_logger, pid=175)
[2020-12-25T22:58:31.799Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../../temp_data/concept idea.png' (host=cc76d8ff70ba, name=network_logger, pid=187)
[2020-12-25T22:58:48.775Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/concept idea.png' (host=cc76d8ff70ba, name=network_logger, pid=199)
[2020-12-25T23:00:48.972Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/concept idea.png' (host=cc76d8ff70ba, name=network_logger, pid=211)
[2020-12-25T23:01:11.684Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=211)
[2020-12-25T23:01:17.716Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=211)
[2020-12-25T23:03:47.349Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=223)
[2020-12-25T23:04:24.825Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=235)
[2020-12-25T23:06:39.556Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=54)
[2020-12-25T23:07:48.145Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=66)
[2020-12-25T23:08:39.945Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=102)
[2020-12-25T23:09:20.244Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=114)
[2020-12-25T23:09:35.885Z] ERROR something went wrong: Error: ENOENT: no such file or directory, open '../../temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=126)
[2020-12-25T23:19:31.040Z] ERROR Error: ENOENT: no such file or directory, open '/srv/backend/temp_data/astro.jpg' (host=cc76d8ff70ba, name=network_logger, pid=193)
[2020-12-25T23:53:59.974Z] ERROR something went wrong: InvalidBucketNameError: Invalid bucket name: profilePics
    at Client.presignedGetObject (/srv/backend/node_modules/minio/dist/main/minio.js:2023:15)
    at Client.<anonymous> (/srv/backend/node_modules/minio/dist/main/helpers.js:69:51)
    at User.generatePictureLink (/srv/backend/src/entity/user.entity.ts:57:19)
    at EntityListenerMetadata.execute (/srv/backend/src/metadata/EntityListenerMetadata.ts:71:45)
    at /srv/backend/src/subscriber/Broadcaster.ts:417:58
    at Array.forEach (<anonymous>)
    at /srv/backend/src/subscriber/Broadcaster.ts:415:45
    at Array.forEach (<anonymous>)
    at Broadcaster.broadcastLoadEventsForAll (/srv/backend/src/subscriber/Broadcaster.ts:396:18)
    at SelectQueryBuilder.<anonymous> (/srv/backend/src/query-builder/SelectQueryBuilder.ts:1992:41) (host=cc76d8ff70ba, name=network_logger, pid=126)
[2020-12-25T23:54:19.503Z] ERROR something went wrong: InvalidBucketNameError: Invalid bucket name: profilePics
    at Client.presignedGetObject (/srv/backend/node_modules/minio/dist/main/minio.js:2023:15)
    at Client.<anonymous> (/srv/backend/node_modules/minio/dist/main/helpers.js:69:51)
    at User.generatePictureLink (/srv/backend/src/entity/user.entity.ts:57:19)
    at EntityListenerMetadata.execute (/srv/backend/src/metadata/EntityListenerMetadata.ts:71:45)
    at /srv/backend/src/subscriber/Broadcaster.ts:417:58
    at Array.forEach (<anonymous>)
    at /srv/backend/src/subscriber/Broadcaster.ts:415:45
    at Array.forEach (<anonymous>)
    at Broadcaster.broadcastLoadEventsForAll (/srv/backend/src/subscriber/Broadcaster.ts:396:18)
    at SelectQueryBuilder.<anonymous> (/srv/backend/src/query-builder/SelectQueryBuilder.ts:1992:41) (host=cc76d8ff70ba, name=network_logger, pid=150)
